### PR TITLE
Import/votes

### PR DESCRIPTION
**Pull request by bdharrington7**
So I'm not really sure what to do here, I started down this path with the idea in mind that since the number of votes is users x posts potentially, I would need to use your machinery to associate a table of votes (where the post id and the user id are both foreign keys) to their respective owners and posts. I know how to use nodebb's system to import the data, I'm just not positive on how to import it in a manner similar way you do for posts ( if that's the right way to do it)

Any ideas? 

this is what the votes table looks like:

    +-----------+--------------+--------+--------+---------------------+
    | CommentID | DiscussionID | UserID | Action | DateUpdated         |
    +-----------+--------------+--------+--------+---------------------+
    |        59 |         NULL |      1 |      1 | 2011-10-31 03:42:35 |
    |      NULL |            5 |      1 |      1 | 2011-10-31 03:45:28 |
    |        60 |         NULL |      2 |      2 | 2011-10-31 03:44:16 |
    |        60 |         NULL |      5 |      1 | 2011-10-31 03:44:26 |

### CODE REVIEW

**Comment by akhoury** [comment]
this looks like a good start,

Looking at this https://github.com/NodeBB/NodeBB/blob/master/src/favourites.js#L104-L131
A vote requires a pid and uid (the new ones, aka NodeBB pid and NodeBB uid) - so the votes need to be imported AFTER the Users and AFTER the Posts.

Possible. Ill take a look this Saturday.

**Comment by bdharrington7** [comment]
Yeah I was planning on using NodeBB's upvote and downvote methods, but I wasn't sure if it made sense to import / save your place the same way we do for posts; because of the way votes are only 1 / person / post, we probably wouldn't need to save out place in case of a crash, but make it idempotent. 

It might be a good time to establish a pattern for this too, it can apply to other "metadata" of a similar nature, like favorites, bookmarks...

**Comment by bdharrington7** [comment]
I'll be online in the NodeBB community if you want to discuss anything :)

**Comment by akhoury** [comment]
i lied, had some unexpected events today. And can't tomorrow. I will try to squeeze it in next week. Sorry :(

**Comment by bdharrington7** [comment]
No worries, it happens. :) Thanks for letting me know!

**Comment by bdharrington7** [comment]
Hi @akhoury, I've got the votes import working, but for some reason I get slightly different imported vote counts each time I run the importer. Did I miss something?

**Comment by bdharrington7** [comment]
Cleaned up this branch so I'm moving the PR

**Pull request closed without merging**
